name: Build & QA
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "18" }
      - run: npm ci
      - run: npm run build
      - run: npm run qa:crawl
      - run: npx lhci autorun --config=tests/lhci.config.js || true
      - name: Upload QA report
        uses: actions/upload-artifact@v4
        with: { name: qa-report, path: reports/* }
      - name: Deploy (Netlify)
        if: ${{ secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
        run: npm run deploy:netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
